package br.edu.ifpe.acsntrs.web.control;

public enum PageEnum
{
	INICIO,
	ALTERA_CADASTRO,
	PREFERENCIAS,
	VER_ESCOLA,
	GERENCIAR_ESCOLA,
	VER_ALUNOS,
	GERENCIAR_ALUNOS,
	GERENCIAR_REPRESENTANTES,
	GERENCIAR_ADMINISTRADORES,
	GERENCIAR_SISTEMA;
}